apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-frontend
  labels:
    app: mp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mp-frontend
  template:
    metadata:
      labels:
        app: mp-frontend
    spec:
      containers:
        - name: mp-frontend
          image: "LATEST_IMAGE"
          ports:
            # - containerPort: 3000
            - protocol: TCP
              port: 3000
              targetPort: 3000
