apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-frontend
  labels:
    app: frontend
data:
  mapUsers: |
    - userarn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:user/${{ secrets.AWS_IAM_USERNAME }}
      username: ${{ secrets.AWS_IAM_USERNAME }}
      groups:
        - system:masters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mp-frontend
  template:
    metadata:
      labels:
        app: mp-frontend
    spec:
      containers:
        - name: mp-frontend
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}
          ports:
            - containerPort: 3000
