apiVersion: v1
kind: Service
metadata:
  name: mp-frontend
  labels:
    app: mp-frontend
spec:
  type: LoadBalancer
  selector:
    app: mp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
