apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-backend
  labels:
    app: mp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mp-backend
  template:
    metadata:
      labels:
        app: mp-backend
    spec:
      containers:
        - name: mp-backend
          image: $LATEST-IMAGE
          ports:
            - containerPort: 5000
