apiVersion: v1
kind: Service
metadata:
  name: mp-backend
  labels:
    app: mp-backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
