on:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"
  workflow_dispatch:

jobs:
  lint:
    name: Lint Backend Python Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lint (flake8)
        run: flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  build:

    name: Build Backend Image
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t mp-backend:latest .

      - name: Run The Docker Image
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend
    
      - name: Check Running App
        run: curl http://localhost:5000/movies

      - name: Review The Logs
        run: docker logs -f mp-backend

      - name: Stop Docker
        run: docker stop

